# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2ffbfc09931200925c3a2a529f0462ffa109f48b842ecbab59b5d6d735b4af5a4675b713e6e72f6eb2d6e82a32432a9ca261d86611280cbd52946223a386f803

test:
  secret_key_base: 1f7f8b6328cf1f91201f98c64b0a86e868c212bac5393245e9c01a8fcdd84d50c8044fcf66d4beab2f6129d3f7d617beccfa5ba3c1c813d0ad1b2f6713d63225

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
